### ISSUE TITLE
TypeNameConverter fails to handle versioned message types

### ISSUE THREAD

**Issue by kylejuliandev** [NServiceBusExtensions/NServiceBus.Serilog#397]
Hi,

I have been recently migrating my projects to .NET 5.0, and as a result I updated many of the NServiceBus nuget packages. I upgraded my nuget reference for NServiceBus.Serilog from 7.2.0 to 7.13.0. Upon upgrading my application I began to test that my messages are executed as they were before I began my migration. During my testing I began to see certain message types, which happened to be versioned, were erroring. Below is the stacktrace of the exception occuring, within the NServiceBus.Serilog package, for every instance of a versioned message (inbound or outbound).

```
System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at NServiceBus.Serilog.TypeNameConverter.FormatForDisplay(String typeName) in /_/src/NServiceBus.Serilog/TypeNameConverter.cs:line 33
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NServiceBus.Serilog.TypeNameConverter.GetName(String longName) in /_/src/NServiceBus.Serilog/TypeNameConverter.cs:line 20
   at InjectIncomingBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`1 next) in /_/src/NServiceBus.Serilog/LogInjection/InjectIncomingBehavior.cs:line 41
   at NServiceBus.InvokeAuditPipelineBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next) in /_/src/NServiceBus.Core/Audit/InvokeAuditPipelineBehavior.cs:line 18
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next) in /_/src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs:line 25
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next) in /_/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs:line 37
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext) in /_/src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs:line 35
   at NServiceBus.Transport.AzureServiceBus.MessagePump.InnerProcessMessage(Task`1 receiveTask)
```

After digging around in the code I believe I found the problematic code. A recent change #384 to the [TypeNameConverter.cs](https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/master/src/NServiceBus.Serilog/TypeNameConverter.cs) overhauled the `GetName(string longName)` method to call `Type.GetType(typeName);`. This causes issues specifically when handling versioned messages as NServicebus populates the message headers (the NServiceBus.EnclosedMessageTypes header) with all versioned types, not just the type that was sent/published. Below is an example of a versioned message header,:

```
MyProject.Events.IMyEventV2, MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;MyProject.Events.IMyEventV1, MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

Wherein IMyEventV2 and IMyEventV1 are defined as:

```csharp
namespace MyProject.Events
{
    public interface IMyEventV2 : MyEventV1
    {
        public string Name { get; set; }
    }
   
    public interface IMyEventV1
    {
        public string Id { get; set; }
    }
}
```

I have subscribers for both `IMyEventV1` and `IMyEventV2`, which might be why NServiceBus includes both assemblies in the headers.

`Type.GetType(typeName);` fails as the above is not a valid [AssemblyQualifiedName](https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname?view=netstandard-2.0).

When I comment out the Serilog code in my NServiceBus setup, my application can handle both versions of the message and execute gracefully.

Many thanks!

*Update 18/05/2021

I have just read that in order to contribute or have issues considered, I would need to be a patron (of which I'm not). So, feel free to close this issue off as I would not meet these requirements.

**Comment by SimonCropp** [comment]
just to confirm, all developers at your company are patrons on open collective? https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq

**Comment by kylejuliandev** [comment]
Hi @SimonCropp 

Negative. I was unaware of the licensing requirements/systems that follow this particular repository. I will be removing all usages of this package from our projects.

Hopefully the issue aids development.

**Comment by SimonCropp** [comment]
@kylejuliandev no worries. note the same applies to all projects under https://github.com/NServiceBusExtensions

**Comment by SimonCropp** [comment]
fix for this has been deployed
